/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_gallery3d_filtershow_filters_ImageFilterDehaze */

#ifndef _Included_com_android_gallery3d_filtershow_filters_ImageFilterDehaze
#define _Included_com_android_gallery3d_filtershow_filters_ImageFilterDehaze
#ifdef __cplusplus
extern "C" {
#endif
#undef com_android_gallery3d_filtershow_filters_ImageFilterDehaze_SIMPLE_ICONS
#define com_android_gallery3d_filtershow_filters_ImageFilterDehaze_SIMPLE_ICONS 1L
/*
 * Class:     com_android_gallery3d_filtershow_filters_ImageFilterDehaze
 * Method:    dehaze_init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_android_gallery3d_filtershow_filters_ImageFilterDehaze_dehaze_1init
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_android_gallery3d_filtershow_filters_ImageFilterDehaze
 * Method:    dehaze_yuv4202rgb
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL
Java_com_android_gallery3d_filtershow_filters_ImageFilterDehaze_dehaze_1yuv4202rgb
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_android_gallery3d_filtershow_filters_ImageFilterDehaze
 * Method:    dehaze_rgb2yuv420
 * Signature: ([B[B[B[B)I
 */
JNIEXPORT jint JNICALL
Java_com_android_gallery3d_filtershow_filters_ImageFilterDehaze_dehaze_1rgb2yuv420
        (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_android_gallery3d_filtershow_filters_ImageFilterDehaze
 * Method:    dehaze_copyRGBData
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL
Java_com_android_gallery3d_filtershow_filters_ImageFilterDehaze_dehaze_1copyRGBData
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_android_gallery3d_filtershow_filters_ImageFilterDehaze
 * Method:    dehaze_process
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL
Java_com_android_gallery3d_filtershow_filters_ImageFilterDehaze_dehaze_1process
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_android_gallery3d_filtershow_filters_ImageFilterDehaze
 * Method:    dehaze_deinit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL
Java_com_android_gallery3d_filtershow_filters_ImageFilterDehaze_dehaze_1deinit
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
