/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sprd_gallery3d_smarterase_SmartErase */

#ifndef _Included_com_sprd_gallery3d_smarterase_SmartErase
#define _Included_com_sprd_gallery3d_smarterase_SmartErase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sprd_gallery3d_smarterase_SmartErase
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint

JNICALL Java_com_sprd_gallery3d_smarterase_SmartEraseNative_init
        (JNIEnv *, jobject);

/*
 * Class:     com_sprd_gallery3d_smarterase_SmartErase
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint

JNICALL Java_com_sprd_gallery3d_smarterase_SmartEraseNative_getVersion
        (JNIEnv *, jobject);

/*
 * Class:     com_sprd_gallery3d_smarterase_SmartErase
 * Method:    deinit
 * Signature: ()I
 */
JNIEXPORT jint

JNICALL Java_com_sprd_gallery3d_smarterase_SmartEraseNative_deinit
        (JNIEnv *, jobject);

/*
 * Class:     com_sprd_gallery3d_smarterase_SmartErase
 * Method:    process
 * Signature: ([B[BII)[B
 */
JNIEXPORT jbyteArray

JNICALL Java_com_sprd_gallery3d_smarterase_SmartEraseNative_process
        (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
