/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sprd_gallery3d_refocus_util_SprdRefocusBokeh */

#ifndef _sprdrealbokeh
#define _sprdrealbokeh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sprd_refocus_bokeh_SprdRealBokeh
 * Method:    bokehInit
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_sprd_refocus_bokeh_SprdRealBokeh_bokehInit
        (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sprd_refocus_bokeh_SprdRealBokeh
 * Method:    bokehClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sprd_refocus_bokeh_SprdRealBokeh_bokehClose
        (JNIEnv *, jobject);

/*
 * Class:     com_sprd_refocus_bokeh_SprdRealBokeh
 * Method:    bokehReFocusPreProcess
 * Signature: ([B[BIII)I
 */
JNIEXPORT jint JNICALL
Java_com_sprd_refocus_bokeh_SprdRealBokeh_bokehReFocusPreProcess
        (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint);

/*
 * Class:     com_sprd_refocus_bokeh_SprdRealBokeh
 * Method:    bokehReFocusGen
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_sprd_refocus_bokeh_SprdRealBokeh_bokehReFocusGen
        (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     com_sprd_refocus_bokeh_SprdRealBokeh
 * Method:    distance
 * Signature: (I[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_sprd_refocus_bokeh_SprdRealBokeh_distance
        (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_sprd_refocus_bokeh_SprdRealBokeh
 * Method:    SrInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_sprd_refocus_bokeh_SprdRealBokeh_SrInit
        (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sprd_refocus_bokeh_SprdRealBokeh
 * Method:    SrProcess
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_sprd_refocus_bokeh_SprdRealBokeh_SrProcess
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_sprd_refocus_bokeh_SprdRealBokeh
 * Method:    SrDeinit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sprd_refocus_bokeh_SprdRealBokeh_SrDeinit
        (JNIEnv *, jobject);

/*
* Class:     com_sprd_refocus_bokeh_SprdRealBokeh
* Method:    depthRotate
* Signature: ([BIII)I
*/
JNIEXPORT jint JNICALL Java_com_sprd_refocus_bokeh_SprdRealBokeh_depthRotate
        (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
