/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sprd_gallery3d_refocus_util_SprdRefocus */

#ifndef _commonblur
#define _commonblur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sprd_refocus_blur_CommonBlur
 * Method:    iSmoothCapInit
 * Signature: (IIFFFIIIIIIIIIIIIIIIII[I[II)V
 */
JNIEXPORT void JNICALL Java_com_sprd_refocus_blur_CommonBlur_iSmoothCapInit
        (JNIEnv *, jobject, jint, jint, jfloat, jfloat, jfloat, jint, jint, jint, jint, jint, jint,
         jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jintArray, jintArray,
         jint, jint);

/*
 * Class:     com_sprd_refocus_blur_CommonBlur
 * Method:    iSmoothCapBlurImage
 * Signature: ([B[BIIIIII[IIII[I[I[I[I[II)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_sprd_refocus_blur_CommonBlur_iSmoothCapBlurImage
        (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jint, jint, jint, jintArray,
         jint, jint, jint, jintArray, jintArray, jintArray, jintArray, jintArray, jint, jint, jint);

/*
 * Class:     com_sprd_refocus_blur_CommonBlur
 * Method:    iSmoothCapDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sprd_refocus_blur_CommonBlur_iSmoothCapDeinit
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
