/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sprd_gallery3d_refocus_util_SprdRefocus */

#ifndef _twoframeblur
#define _twoframeblur
#ifdef __cplusplus
extern "C" {
#endif

bool mIsTwoFrameBokeh = false;

/*
 * Class:     com_sprd_refocus_blur_TwoFrameBlur
 * Method:    twoFrameBokehInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_sprd_refocus_blur_TwoFrameBlur_twoFrameBokehInit
        (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint,
         jint, jint, jint, jint, jint, jint, jintArray, jintArray, jintArray, jintArray);


/*
 * Class:     com_sprd_refocus_blur_TwoFrameBlur
 * Method:    twoFrameBokeh
 * Signature: ([B[BIII)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_sprd_refocus_blur_TwoFrameBlur_twoFrameBokeh
        (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint);

/*
 * Class:     com_sprd_refocus_blur_TwoFrameBlur
 * Method:    twoFrameBokehDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_sprd_refocus_blur_TwoFrameBlur_twoFrameBokehDeinit
        (JNIEnv *, jobject);

/*
 * Class:     com_sprd_refocus_blur_TwoFrameBlur
 * Method:    twoFrameDepthInit
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_sprd_refocus_blur_TwoFrameBlur_twoFrameDepthInit
        (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif