/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sprd_blending_ImageBlending */

#ifndef _Included_com_sprd_blending_ImageBlending
#define _Included_com_sprd_blending_ImageBlending
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sprd_blending_ImageBlending
 * Method:    ImageBlendingInit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sprd_blending_ImageBlending_ImageBlendingInit
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_sprd_blending_ImageBlending
 * Method:    _getTargetImg
 * Signature: (II[BII[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sprd_blending_ImageBlending__1getTargetImg
        (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint, jbyteArray, jfloat);

/*
 * Class:     com_sprd_blending_ImageBlending
 * Method:    _doBlending
 * Signature: (II[BII[BII[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sprd_blending_ImageBlending__1doBlending
        (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray,
         jint, jint, jint, jint, jfloat, jfloat);

/*
 * Class:     com_sprd_blending_ImageBlending
 * Method:    _ImageBlendingDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sprd_blending_ImageBlending__1ImageBlendingDeinit
        (JNIEnv *, jobject);

/*
 * Class:     com_sprd_blending_ImageBlending
 * Method:    _ExtractFg2Pts
 * Signature: (II[B[BIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sprd_blending_ImageBlending__1ExtractFg2Pts
        (JNIEnv *, jobject, jint, jint, jbyteArray, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_sprd_blending_ImageBlending
 * Method:    _ExtractFgUpdate
 * Signature: ([I[IIZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sprd_blending_ImageBlending__1ExtractFgUpdate
        (JNIEnv *, jobject, jintArray, jintArray, jint, jboolean);

/*
 * Class:     com_sprd_blending_ImageBlending
 * Method:    _ExtractFgScaling
 * Signature: ([BIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sprd_blending_ImageBlending__1ExtractFgScaling
        (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_sprd_blending_ImageBlending
 * Method:    _ExtractFgCreatefbobject
 * Signature: (II[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_sprd_blending_ImageBlending__1ExtractFgCreatefbobject
        (JNIEnv *, jobject, jint, jint, jbyteArray, jbyteArray, jint start_x, jint start_y,
         jint box_width, jint box_height);

/*
 * Class:     com_sprd_blending_ImageBlending
 * Method:    _verify_icon_pos
 * Signature: ([BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_sprd_blending_ImageBlending__1verify_1icon_1pos
        (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jint, jint, jfloat, jfloat);

/*
 * Class:     com_sprd_blending_ImageBlending
 * Method:    _ExtractFg_saveUpdate
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_sprd_blending_ImageBlending__1ExtractFg_1saveUpdate
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_sprd_blending_ImageBlending
 * Method:    _ExtractFg_extractUpdate
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_sprd_blending_ImageBlending__1ExtractFg_1extractUpdate
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_sprd_blending_ImageBlending
 * Method:    _Extract_depthScaling
 * Signature: ([BIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sprd_blending_ImageBlending__1Extract_1depthScaling
        (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     com_sprd_blending_ImageBlending
 * Method:    _ExtractFg_depth_rotate
 * Signature: ([BIIII)[B
 */
JNIEXPORT jint JNICALL Java_com_sprd_blending_ImageBlending__1ExtractFg_1depth_1rotate
        (JNIEnv *env, jobject obj, jbyteArray depth, jint width, jint height, jint rotate);

#ifdef __cplusplus
}
#endif
#endif
